### ISSUE TITLE
[FEATURE]: Add Members Section w/ Images

### ISSUE THREAD

**Issue by haIIux** [0xOpenBytes/Site#1]
This feature would add the list of members / contributors to our website under the About section. Ideally, this will display our respective Github profile pictures in a circle. 

They all must..
1. Be the same shape.
2. Have a label of either the persons name or their Github username.
3. Should be links that open a new tab to the users Github page.

The current members are as follows...

https://github.com/0xLeif
https://github.com/haIIux
https://github.com/FullQueueDeveloper
https://github.com/parshav

While there is no specific framework requirements, it must utilize Astro and preferably not add a bunch of dependencies that need to be maintained.

**Comment by 0xLeif** [comment]
Current site implementation: https://openbytes.dev/github/
