### ISSUE TITLE
Implement Website Analytics

### ISSUE THREAD

**Issue by 0xLeif** [0xOpenBytes/Site#6]
Goal
The goal behind implementing website analytics is to determine overall website traffic in addition to strategicly tracking popular articles, content and more. Visitor privacy is important as we ideally will track no specific details regarding the visitor.

Options
- [TelemetryDeck](https://telemetrydeck.com/) (Free)
    - Since this is a Swift based static site, TelemetryDeck should be able to be implemented quite easily using SPM.
- [Netlify](https://www.netlify.com/) ($9.00 / mo)
    - This offers hosting for free, with analytics for $9.00 a month.
- [Plausible](https://plausible.io/) ($9.00 / mo)
    - This was an option brought up by a member in the Discord. Unsure of complete implementation but I assume it's JS based.
    
    
 [source](https://github.com/0xOpenBytes/Publish-Site/issues/19)

**Comment by haIIux** [comment]
I see we mentioned that we wanted this closed [within this PR](https://github.com/0xOpenBytes/Site/pull/32) but I happen to notice this is still open.

Do we just need to close it?
